module.exports = {
  serverUrl: process.env.SERVER_URL || 'http://localhost:5000',
  serverPort: process.env.PORT || 5000,
  mongodbUrl: process.env.MONGODB_URI || 'mongodb://localhost:27017/bkfighter',
  maxPlayers: 4,
  tickRate: 60,
  clientPort: 3000,
  isDevelopment: process.env.NODE_ENV !== 'production',
  logLevel: process.env.LOG_LEVEL || 'info',
  jwtSecret: process.env.JWT_SECRET || 'your-secret-key',
  defaultHealth: 100,
  defaultSpeed: 5,
  enableMultiplayer: true,
  enableAI: false,
};