version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017/bkfighter
    depends_on:
      - mongodb
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bkfighter
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: