version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - SERVER_URL=http://server:3000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/bk-fighter
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: