version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: bk-fighter-3d-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bk-fighter-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: bk-fighter-3d-server
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/bk-fighter-3d
    networks:
      - bk-fighter-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: bk-fighter-3d-client
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - bk-fighter-network

networks:
  bk-fighter-network:
    driver: bridge

volumes:
  mongodb_data: