---
- hosts: all
  become: yes
  vars:
    app_dir: /opt/bk-fighter-3d
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Node.js and npm
      apt:
        name: 
          - nodejs
          - npm
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB service
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy application files
      copy:
        src: ./
        dest: "{{ app_dir }}"

    - name: Install app dependencies
      npm:
        path: "{{ app_dir }}"

    - name: Install PM2
      npm:
        name: pm2
        global: yes

    - name: Start the application with PM2
      command: pm2 start {{ app_dir }}/server/server.js
      environment:
        SERVER_URL: "{{ lookup('env', 'SERVER_URL') }}"
        SERVER_PORT: "{{ lookup('env', 'SERVER_PORT') }}"
        MONGODB_URL: "{{ lookup('env', 'MONGODB_URL') }}"