---
- name: Deploy BK-fighter-3D
  hosts: all
  become: yes
  vars:
    app_dir: /opt/bk-fighter-3d
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages
      package:
        name:
          - docker
          - docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create project directory
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"

    - name: Copy Dockerfile
      copy:
        src: Dockerfile
        dest: "{{ app_dir }}/Dockerfile"

    - name: Copy application files
      copy:
        src: ./
        dest: "{{ app_dir }}"
        exclude:
          - .git
          - node_modules

    - name: Build and start Docker containers
      docker_compose:
        project_src: "{{ app_dir }}"
        build: yes
        pull: yes
        state: present