---
- name: Setup BK-Fighter-3D server
  hosts: all
  become: yes
  vars:
    app_dir: /var/www/bk-fighter-3d

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nodejs
          - npm
          - git
          - docker.io
          - docker-compose
        state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/Axle-Bucamp/BK-fighter-3D.git'
        dest: "{{ app_dir }}"
        version: main

    - name: Install npm dependencies
      npm:
        path: "{{ app_dir }}"

    - name: Build the application
      command: npm run build
      args:
        chdir: "{{ app_dir }}"

    - name: Start the application with Docker Compose
      docker_compose:
        project_src: "{{ app_dir }}"
        state: present

    - name: Ensure the application starts on boot
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Print success message
      debug:
        msg: "BK-Fighter-3D server setup complete!"