---
- name: Deploy BK-Fighter-3D
  hosts: all
  become: yes
  vars:
    app_dir: /opt/bk-fighter-3d
    node_version: "14.x"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - nodejs
          - npm
          - mongodb
        state: present

    - name: Clone the repository
      git:
        repo: 'https://github.com/Axle-Bucamp/BK-fighter-3D.git'
        dest: "{{ app_dir }}"
        version: main

    - name: Install app dependencies
      npm:
        path: "{{ app_dir }}"

    - name: Build the app
      command: npm run build
      args:
        chdir: "{{ app_dir }}"

    - name: Create systemd service file
      template:
        src: bk-fighter-3d.service.j2
        dest: /etc/systemd/system/bk-fighter-3d.service

    - name: Start and enable the service
      systemd:
        name: bk-fighter-3d
        state: started
        enabled: yes

    - name: Ensure MongoDB is running
      systemd:
        name: mongodb
        state: started
        enabled: yes

    - name: Open firewall ports
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "80"
        - "443"
        - "5000"

- name: Configure Nginx as reverse proxy
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create Nginx config file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/bk-fighter-3d

    - name: Enable Nginx config
      file:
        src: /etc/nginx/sites-available/bk-fighter-3d
        dest: /etc/nginx/sites-enabled/bk-fighter-3d
        state: link

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted